{
 "cells": [
  {
   "metadata": {},
   "cell_type": "raw",
   "source": [
    "# Install required libraries (run once)\n",
    "!pip install scipy scikit-learn matplotlib pandas liac-arff\n",
    "\n",
    "import arff\n",
    "import pandas as pd\n",
    "from scipy.cluster.hierarchy import dendrogram, linkage\n",
    "import matplotlib.pyplot as plt\n",
    "from sklearn.preprocessing import LabelEncoder\n",
    "\n",
    "# Load ARFF file\n",
    "def load_arff(file_path):\n",
    "    with open(file_path, 'r') as\n",
    "        dataset = arff.load(f)\n",
    "    df = pd.DataFrame(dataset['data'])\n",
    "    df.columns = [attr[0] for attr in dataset['attributes']]\n",
    "    return df\n",
    "\n",
    "# Preprocess data (convert categorical to numeric)\n",
    "def preprocess(df):\n",
    "    for col in df.columns:\n",
    "        if df[col].dtype == 'object':\n",
    "            le = LabelEncoder()\n",
    "            df[col] = le.fit_transform(df[col].astype(str))\n",
    "    return df\n",
    "\n",
    "# Hierarchical clustering function\n",
    "def hierarchical_clustering(df, title):\n",
    "    linked = linkage(df, method='ward')\n",
    "\n",
    "    plt.figure(figsize=(10, 5))\n",
    "    dendrogram(linked)\n",
    "    plt.title(f\"Dendrogram - {title}\")\n",
    "    plt.xlabel(\"Data Points\")\n",
    "    plt.ylabel(\"Distance\")\n",
    "    plt.show()\n",
    "\n",
    "# Load datasets\n",
    "employee_df = load_arff(\"employee.arff\")\n",
    "student_df = load_arff(\"student.arff\")\n",
    "\n",
    "# Preprocess\n",
    "employee_df = preprocess(employee_df)\n",
    "student_df = preprocess(student_df)\n",
    "\n",
    "# Apply clustering\n",
    "hierarchical_clustering(employee_df, \"Employee Dataset\")\n",
    "hierarchical_clustering(student_df, \"Student Dataset\")"
   ],
   "id": "df164e0537518171"
  }
 ],
 "metadata": {},
 "nbformat": 4,
 "nbformat_minor": 5
}
